import { expect, it } from 'vitest';
import { createHash } from 'node:crypto';
import { mkdtempSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fullTransactionSchema } from '../src/helius/schemas.js';
import type { FullTransaction } from '../src/helius/schemas.js';
import type { NormalizationProvenance } from '../src/normalization/types.js';
import type { DistributionEvidenceInput } from '../src/payout-evidence/types.js';
import { normalizeTransaction } from '../src/normalization/normalizer.js';
import { processDirty } from '../src/scanner/classifier.js';
import { buildReport } from '../src/scanner/report.js';
import { SqliteRewardsStore } from '../src/storage/sqlite.js';
import { removeTempFolder } from './temp-folder.js';

// Captured public provider evidence, not generated by demoTransaction or a synthetic feed helper.
const capture = JSON.parse(readFileSync(new URL('./fixtures/captured/payout-4Am7wVR.json', import.meta.url), 'utf8')) as {
  kind: string; network: 'mainnet-beta'; observationId: string; transaction: FullTransaction;
  transactionProvenance: NormalizationProvenance; feed: DistributionEvidenceInput;
};
const signature = '4Am7wVRc7nCvq5wf2D7nfEFbfvyg5Tvya5k7z84crMYTTtirsj2S7KNeqyrKdyt21X1c2FZEW2mfq7sJvHjK4F4A';
const recipient = 'Ap8XtRRi9Ywmw4YcGN8i46eVv4PkFxCvBAbpeVbYh1s8';
// A synthetic wallet that is not among the transaction's recipients.
const outsider = '8'.repeat(32);
const mint = 'PreLWGkkeqG1s4HEfFZSy9moCrJ7btsHuUtfcCeoRua';
const sha = (value: unknown) => createHash('sha256').update(JSON.stringify(value)).digest('hex');

it('replays captured 4Am7wVR evidence into exactly 1629660 unpriced raw units for its actual recipient', async () => {
  expect(capture.kind).toBe('captured-provider-evidence');
  expect(sha(capture.transaction)).toBe('034b3efc838dad32b89d7d01481ee4098e22b1d5c615864ea4ec9015d636fe03');
  expect(sha(capture.feed)).toBe('33fbbea978b8219f5b53980d962df4314201c2a78e74123ea550ade03a50ca6e');
  const tx = fullTransactionSchema.parse(capture.transaction);
  expect(tx.transaction.signatures[0]).toBe(signature);
  expect(capture.transactionProvenance).toMatchObject({ source: 'helius', retrievedAt: '2026-09-21T06:44:43.914Z', commitment: 'finalized' });
  const feedRow = capture.feed.distributions[0]!.rows[0]!;
  expect(feedRow).toMatchObject({ sourceIds: ['source-2'], value: { signature, mint: 'C83U6phmTnNdJXGXH1R7qqSScKM2rYk6yReGnPz8A12M', quoteMint: mint, amountRaw: '25424126' } });
  expect(capture.feed.sources).toHaveLength(1);
  expect(capture.feed.sources[0]).toMatchObject({ id: 'source-2', endpoint: '/rewards?limit=100', outcome: 'success', retrievedAt: '2026-09-21T06:23:01.491Z' });
  const normalized = normalizeTransaction({ network: capture.network, wallet: recipient, transaction: tx, provenance: capture.transactionProvenance });
  expect(normalized.transfers).toHaveLength(17);
  expect(normalized.transfers.reduce((sum, transfer) => sum + BigInt(transfer.grossAmountRaw), 0n)).toBe(25424126n);
  expect(normalized.transfers.reduce((sum, transfer) => sum + BigInt(transfer.netCreditRaw!), 0n)).toBe(25169876n);
  expect(normalized.transfers.filter(transfer => transfer.destinationOwner.value === recipient)).toMatchObject([{
    grossAmountRaw: '1646122', netCreditRaw: '1629660',
    source: '42Ygu2TKMDkiWArhxg8Q7cskA3jGoBGhiWzvBujZNeBy',
    authority: 'HuBMeYW3aDn8BH65fo8xxbP4oiexyup8udzKyccgi8Ga',
    destination: '8wL6Ys4CnhChgJ1pZKTdM1RZrprazd9p7ASkN3Cwp1mr',
  }]);
  const directory = mkdtempSync(join(tmpdir(), 'rewards-captured-'));
  const path = join(directory, 'replay.sqlite'); let store = new SqliteRewardsStore(path);
  try {
    store.atomic(() => {
      for (const wallet of [recipient, outsider]) {
        store.saveWallet({ network: capture.network, wallet, trackingStart: tx.blockTime! - 864000, cutoff: tx.blockTime! + 1, lastSync: null });
        store.saveCache(`dataset:${capture.network}:${wallet}`, { value: 'Captured provider evidence: one public payout; no wallet-history coverage', expiresAt: Number.MAX_SAFE_INTEGER });
        store.watch(capture.network, signature, wallet);
      }
      // Membership is derived only from the original official row. No price or invented feed is supplied.
      store.saveQuote(capture.network, { mint: feedRow.value.quoteMint, retrievedAt: capture.feed.sources[0]!.retrievedAt,
        membershipEvidence: [{ kind: 'distribution', launchMint: feedRow.value.mint, endpoint: capture.feed.sources[0]!.endpoint, retrievedAt: capture.feed.sources[0]!.retrievedAt }] });
      store.addFeed(capture.feed); store.addTransaction(capture.network, tx, capture.transactionProvenance);
    });
    expect(processDirty(store, capture.network)).toBe(1);
    const report = buildReport(store, recipient);
    expect(report.counts).toEqual({ confirmed: 1, attributed: 0, excluded: 0, unknown_candidate: 0 });
    expect(report.details[0]).toMatchObject({ signature, wallet: recipient, basis: 'official_feed', netRaw: '1629660', grossRaw: '1646122', mint,
      evidenceIds: [capture.observationId], supportingSignatures: [signature] });
    for (const period of [report.rolling168h, report.latest24h, report.cumulative, report.utcDays[0]!]) {
      expect(period.assets).toMatchObject([{ mint, raw: '1629660', decimals: 9, receipts: 1, currentUsd: null }]);
      expect(period.unpriced).toHaveLength(1); expect(period.currentUsd).toBeNull();
      expect(period.pricingCoverage).toEqual({ pricedWalletCreditGroups: 0, totalWalletCreditGroups: 1, pricedMints: 0, totalMints: 1 });
    }
    expect(report.rolling168h.dailyAverageUsd).toBeNull(); expect(report.coverage.verifiedZero).toBe(false);
    expect(report.coverage.retrieval).toBe('partial');
    expect(buildReport(store, outsider).counts.confirmed).toBe(0);
    store.close(); store = new SqliteRewardsStore(path);
    store.addTransaction(capture.network, tx, capture.transactionProvenance); store.addFeed(capture.feed);
    expect(processDirty(store, capture.network)).toBe(0);
    expect(buildReport(store, recipient)).toEqual(report);
  } finally { store.close(); await removeTempFolder(directory); }
});
